version: '3'

services:
  backend:
    restart: unless-stopped
    image: juridico_back:latest
    volumes:
      - "./Juridico_back/juridico_site/db/:/backend/juridico_site/db/"
    ports:
      - 8000:8000
    container_name: juridico_back

  frontend:
    restart: unless-stopped
    image: midemarc/juridico_front:latest
    ports:      
      - 4200:80
    container_name: juridico_front
